### ISSUE TITLE
Documentation for installation/running

### ISSUE THREAD

**Issue by sarthakpati** [jw4hv/deepflash#1]
Hi,

Thanks for making your code available here! The work is very interesting and I am interested to try it out with some of my data.

It would be very helpful if you can update your documentation with some detailed installation instructions (conda or pip commands) along with some examples of how to run this.

Cheers,
S

**Comment by jw4hv** [comment]
Hi Sarthak, thanks for your comments. Sorry for now I do not have access to my latest version due to the COVID 19 situation. (Our research building is closed and the hard-drive includes the code is in that building). I will work on this issue as fast as possible and let you know the updates. Also, I will have a MATLAB version uploaded as well later. Thanks.
